---
title: "deltaZ_posterior_mean"
output: html_document
---

```{r}
source('~/Runcie Lab/SparseFactorMixedModel_v2/R_BSFG/BSFG_functions.R')
setwd("~/Runcie Lab/SparseFactorMixedModel_v2/MCMC/5/5/Lambda1.5_delta2shape3")
BSFGOld = "BSFG_state.RData"
BSFGNew = "BSFG_fixedlambda65.RData"
BSFGStar = "BSFG_fixedlambda75.RData"
#BSFGNew = "BSFG_fixedlambdaR5.RData"
#BSFGStar = "BSFG_fixedlambdaS5.RData"
target = "F_h2"
load(BSFGOld)
traitnames = BSFG_state$traitnames
#old.traces.G = G_Traces_Comp(BSFG_state)
old.G = G_Matrix_Comp(BSFG_state)
p = BSFG_state$run_variables$p
spn = dim(BSFG_state$Posterior[[target]])[2]
# posterior mean
# do this in case the value of k differ for this two models and there in no lambda in BSFG_state_fixed case
Lambda = BSFG_state$Posterior$Lambda
load(BSFGNew)
BSFG_state$Posterior$Lambda = Lambda
new.G = G_Matrix_Comp(BSFG_state)

load(BSFGStar)
BSFG_state$Posterior$Lambda = Lambda
star.G = G_Matrix_Comp(BSFG_state)
#new.traces.G = G_Traces_Comp(BSFG_state)


# The distance of two matrix(in predicted phenotype value/level)
#selection gradient
beta = 0.3609
beta.v = c(0,beta,rep(0,16))
traces.traits = matrix(,p,spn)

#old.G in list form
old.traces.traits = sapply(old.G,function(x)x%*%beta.v)
old.traits.posmean = apply(old.traces.traits,1,mean)
new.traces.traits = sapply(new.G,function(x)x%*%beta.v)
new.traits.posmean = apply(new.traces.traits,1,mean)
star.traces.traits = sapply(star.G,function(x)x%*%beta.v)
star.traits.posmean = apply(star.traces.traits,1,mean)
#boxplot(old.traces_traits[2,])
#boxplot(t(old.traces.traits))
#boxplot(new.traces_traits[2,])
#boxplot(t(new.traces.traits))
# use ggplot 
traces.traits.df = data.frame(c(c(old.traces.traits),c(new.traces.traits),c(star.traces.traits)))
traces.traits.df$model = rep(c("old","new","star"),each=spn*p)
traces.traits.df$traits = rep(traitnames,3*spn)
names(traces.traits.df) = c("response","model","traits")
library(ggplot2)
#ggplot(traces.traits.df,aes(x =traits,y=response,col=model,fill=model))+
 # geom_boxplot()
#plot(x=rep(1:18,2),y=c(old.traits.posmean,new.traits.posmean),col=rep(c(1,2),eac#h=18),type = "o")
ggplot(traces.traits.df, aes(x = traits, y = response, color=model))+
  #geom_boxplot(alpha = 0.5)+
  scale_color_manual(breaks = c("old", "new", "star"),
                     values=c("green", "red", "blue"))+
  #scale_fill_manual(breaks = c("old", "new", "star"),
  #                  values=c("green", "red", "blue"))+
  ggtitle("The distribution of variance (Latent traits)")+
  scale_color_discrete(breaks = c("old", "new", "star"),labels=c("LconG3", "LhighG3", "LlowG3"))+
 # scale_fill_discrete(breaks = c("old", "new", "star"),labels=c("LconG3", "LhighG3", "LlowG3"))+
  ylab("Response")+
  geom_errorbar(aes(ymin=quantile(response,0.025), ymax=quantile(response,0.975)), width=.1, position=pd)

```

```{r}
#when lambda is not fixed
source('~/Runcie Lab/SparseFactorMixedModel_v2/R_BSFG/BSFG_functions.R')
setwd("~/Runcie Lab/SparseFactorMixedModel_v2/MCMC/5/5/Lambda1.5_delta2shape3")
BSFGOld = "BSFG_state.RData"
BSFGNew = "BSFG_state14.RData"
BSFGStar = "BSFG_state17.RData"
target = "F_h2"
load(BSFGOld)
traitnames = BSFG_state$traitnames
#old.traces.G = G_Traces_Comp(BSFG_state)
old.G = G_Matrix_Comp(BSFG_state)
p = BSFG_state$run_variables$p
spn = dim(BSFG_state$Posterior[[target]])[2]
load(BSFGNew)
new.G = G_Matrix_Comp(BSFG_state)
load(BSFGStar)
#BSFG_state$Posterior$Lambda = Lambda
star.G = G_Matrix_Comp(BSFG_state)

beta = 0.3609
beta.v = c(0,beta,rep(0,16))
traces.traits = matrix(,p,spn)

#old.G in list form
old.traces.traits = sapply(old.G,function(x)x%*%beta.v)
old.traits.posmean = apply(old.traces.traits,1,mean)
new.traces.traits = sapply(new.G,function(x)x%*%beta.v)
new.traits.posmean = apply(new.traces.traits,1,mean)
star.traces.traits = sapply(star.G,function(x)x%*%beta.v)
star.traits.posmean = apply(star.traces.traits,1,mean)
#boxplot(old.traces_traits[2,])
#boxplot(t(old.traces.traits))
#boxplot(new.traces_traits[2,])
#boxplot(t(new.traces.traits))
# use ggplot 
traces.traits.df = data.frame(c(c(old.traces.traits),c(new.traces.traits),c(star.traces.traits)))
traces.traits.df$model = rep(c("old","new","star"),each=spn*p)
traces.traits.df$traits = rep(traitnames,3*spn)
names(traces.traits.df) = c("response","model","traits")
library(ggplot2)
ggplot(traces.traits.df,aes(x =traits,y=response,col=model))+
  geom_boxplot()
```
