# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_coefs_parallel_sparse_c <- function(Y, W, h2, tot_Y_prec, prior_mean, prior_prec, invert_aI_bZAZ, grainSize) {
    .Call('BSFG_sample_coefs_parallel_sparse_c', PACKAGE = 'BSFG', Y, W, h2, tot_Y_prec, prior_mean, prior_prec, invert_aI_bZAZ, grainSize)
}

sample_tot_prec_sparse_c <- function(Y, h2, tot_Y_prec_shape, tot_Y_prec_rate, invert_aI_bZAZ) {
    .Call('BSFG_sample_tot_prec_sparse_c', PACKAGE = 'BSFG', Y, h2, tot_Y_prec_shape, tot_Y_prec_rate, invert_aI_bZAZ)
}

sample_h2s_discrete_given_p_sparse_c <- function(Y, h2_divisions, h2_priors, Tot_prec, invert_aI_bZAZ) {
    .Call('BSFG_sample_h2s_discrete_given_p_sparse_c', PACKAGE = 'BSFG', Y, h2_divisions, h2_priors, Tot_prec, invert_aI_bZAZ)
}

sample_randomEffects_parallel_sparse_c <- function(Y, Z, tot_prec, h2, invert_aZZt_Ainv, grainSize) {
    .Call('BSFG_sample_randomEffects_parallel_sparse_c', PACKAGE = 'BSFG', Y, Z, tot_prec, h2, invert_aZZt_Ainv, grainSize)
}

sample_means_parallel_c <- function(Y_tilde, resid_Y_prec, E_a_prec, invert_aA_bZtZ, grainSize) {
    .Call('BSFG_sample_means_parallel_c', PACKAGE = 'BSFG', Y_tilde, resid_Y_prec, E_a_prec, invert_aA_bZtZ, grainSize)
}

sample_factors_scores_sparse_c <- function(Y_tilde, Z, Lambda, resid_Y_prec, F_a, F_e_prec) {
    .Call('BSFG_sample_factors_scores_sparse_c', PACKAGE = 'BSFG', Y_tilde, Z, Lambda, resid_Y_prec, F_a, F_e_prec)
}

GSVD_2_c <- function(A, B) {
    .Call('BSFG_GSVD_2_c', PACKAGE = 'BSFG', A, B)
}

sample_delta_c <- function(delta, tauh, Lambda_prec, delta_1_shape, delta_1_rate, delta_2_shape, delta_2_rate, Lambda2, times = 1L) {
    .Call('BSFG_sample_delta_c', PACKAGE = 'BSFG', delta, tauh, Lambda_prec, delta_1_shape, delta_1_rate, delta_2_shape, delta_2_rate, Lambda2, times)
}

