# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_candidate_states <- function(h2s_matrix, step_size, old_state) {
    .Call(BSFG_find_candidate_states, h2s_matrix, step_size, old_state)
}

LDLt_sparse <- function(A) {
    .Call(BSFG_LDLt_sparse, A)
}

LDLt_notSparse <- function(A) {
    .Call(BSFG_LDLt_notSparse, A)
}

SxD <- function(X, Y) {
    .Call(BSFG_SxD, X, Y)
}

SxS <- function(X, Y) {
    .Call(BSFG_SxS, X, Y)
}

uncorrelated_prec_mat <- function(h2, tot_prec, s) {
    .Call(BSFG_uncorrelated_prec_mat, h2, tot_prec, s)
}

sample_coefs_parallel_sparse_c_Eigen <- function(Y, X, resid_prec, prior_mean, prior_prec, grainSize) {
    .Call(BSFG_sample_coefs_parallel_sparse_c_Eigen, Y, X, resid_prec, prior_mean, prior_prec, grainSize)
}

sample_coefs_parallel_sparse_missing_c_Eigen <- function(Eta, W, h2, tot_Eta_prec, prior_mean, prior_prec, invert_aI_bZKZ, grainSize) {
    .Call(BSFG_sample_coefs_parallel_sparse_missing_c_Eigen, Eta, W, h2, tot_Eta_prec, prior_mean, prior_prec, invert_aI_bZKZ, grainSize)
}

sample_coefs_set_c <- function(model_matrices, h2s, tot_Eta_prec, prior_mean, prior_prec, n, grainSize) {
    .Call(BSFG_sample_coefs_set_c, model_matrices, h2s, tot_Eta_prec, prior_mean, prior_prec, n, grainSize)
}

get_fitted_set_c <- function(model_matrices, coefs, grainSize) {
    .Call(BSFG_get_fitted_set_c, model_matrices, coefs, grainSize)
}

sample_cis_coefs_parallel_sparse_c_Eigen <- function(Y, X, cis_genotypes, resid_prec, prior_mean, prior_prec, cis_effect_index, grainSize) {
    .Call(BSFG_sample_cis_coefs_parallel_sparse_c_Eigen, Y, X, cis_genotypes, resid_prec, prior_mean, prior_prec, cis_effect_index, grainSize)
}

sample_randomEffects_parallel_sparse_c_Eigen <- function(Eta, Z, tot_prec, h2, invert_aZZt_Kinv, grainSize) {
    .Call(BSFG_sample_randomEffects_parallel_sparse_c_Eigen, Eta, Z, tot_prec, h2, invert_aZZt_Kinv, grainSize)
}

sample_randomEffects_parallel_sparse_missing_c_Eigen <- function(Eta, tot_prec, h2, invert_aZZt_Kinv, r, grainSize) {
    .Call(BSFG_sample_randomEffects_parallel_sparse_missing_c_Eigen, Eta, tot_prec, h2, invert_aZZt_Kinv, r, grainSize)
}

sample_factors_scores_sparse_c_Eigen <- function(Eta_tilde, prior_mean, Lambda, resid_Eta_prec, F_e_prec) {
    .Call(BSFG_sample_factors_scores_sparse_c_Eigen, Eta_tilde, prior_mean, Lambda, resid_Eta_prec, F_e_prec)
}

sample_factors_scores_sparse_missing_c_Eigen <- function(Eta_tilde, prior_mean, Lambda, resid_Eta_prec, F_e_prec, Y_row_obs_sets, grainSize) {
    .Call(BSFG_sample_factors_scores_sparse_missing_c_Eigen, Eta_tilde, prior_mean, Lambda, resid_Eta_prec, F_e_prec, Y_row_obs_sets, grainSize)
}

tot_prec_scores_c <- function(Y, resid_prec) {
    .Call(BSFG_tot_prec_scores_c, Y, resid_prec)
}

tot_prec_scores_missing_c <- function(Eta, h2, invert_aI_bZKZ) {
    .Call(BSFG_tot_prec_scores_missing_c, Eta, h2, invert_aI_bZKZ)
}

log_p_h2s_fast <- function(QtEta, tot_Eta_prec, discrete_priors, s, grainSize) {
    .Call(BSFG_log_p_h2s_fast, QtEta, tot_Eta_prec, discrete_priors, s, grainSize)
}

log_p_h2s_fast_missing <- function(Eta, tot_Eta_prec, discrete_priors, invert_aI_bZKZ, grainSize) {
    .Call(BSFG_log_p_h2s_fast_missing, Eta, tot_Eta_prec, discrete_priors, invert_aI_bZKZ, grainSize)
}

sample_h2s_discrete_MH_fast_c <- function(QtEta, tot_Eta_prec, discrete_priors, h2_index, h2s_matrix, s, step_size, grainSize) {
    .Call(BSFG_sample_h2s_discrete_MH_fast_c, QtEta, tot_Eta_prec, discrete_priors, h2_index, h2s_matrix, s, step_size, grainSize)
}

sample_h2s_discrete_MH_fast_missing_c <- function(Eta, tot_Eta_prec, discrete_priors, h2_index, h2s_matrix, step_size, invert_aI_bZKZ, grainSize) {
    .Call(BSFG_sample_h2s_discrete_MH_fast_missing_c, Eta, tot_Eta_prec, discrete_priors, h2_index, h2s_matrix, step_size, invert_aI_bZKZ, grainSize)
}

sample_MME_single_diagK_c <- function(y, W, prior_mean, prior_prec, chol_R, tot_Eta_prec, randn_theta, randn_e) {
    .Call(BSFG_sample_MME_single_diagK_c, y, W, prior_mean, prior_prec, chol_R, tot_Eta_prec, randn_theta, randn_e)
}

sample_MME_fixedEffects_c <- function(Y, W, Sigma_Choleskys, h2s_index, tot_Eta_prec, prior_mean, prior_prec, randn_theta, randn_e, grainSize) {
    .Call(BSFG_sample_MME_fixedEffects_c, Y, W, Sigma_Choleskys, h2s_index, tot_Eta_prec, prior_mean, prior_prec, randn_theta, randn_e, grainSize)
}

sample_MME_fixedEffects_cis_c <- function(Y, W, cis_genotypes, Sigma_Choleskys, h2s_index, tot_Eta_prec, prior_mean, prior_prec, randn_theta, randn_e, randn_cis, cis_effect_index, grainSize) {
    .Call(BSFG_sample_MME_fixedEffects_cis_c, Y, W, cis_genotypes, Sigma_Choleskys, h2s_index, tot_Eta_prec, prior_mean, prior_prec, randn_theta, randn_e, randn_cis, cis_effect_index, grainSize)
}

sample_MME_single_diagR <- function(Y, W, chol_C, pe, chol_K_inv, tot_Eta_prec, randn_theta, randn_e) {
    .Call(BSFG_sample_MME_single_diagR, Y, W, chol_C, pe, chol_K_inv, tot_Eta_prec, randn_theta, randn_e)
}

sample_MME_ZKZts_c <- function(Y, W, tot_Eta_prec, randomEffect_C_Choleskys, h2s, h2s_index, randn_theta, randn_e, grainSize) {
    .Call(BSFG_sample_MME_ZKZts_c, Y, W, tot_Eta_prec, randomEffect_C_Choleskys, h2s, h2s_index, randn_theta, randn_e, grainSize)
}

tot_prec_scores <- function(Y, Sigma_Choleskys, h2s_index, grainSize) {
    .Call(BSFG_tot_prec_scores, Y, Sigma_Choleskys, h2s_index, grainSize)
}

log_p_h2s <- function(Y, tot_Eta_prec, Sigma_Choleskys, discrete_priors, grainSize) {
    .Call(BSFG_log_p_h2s, Y, tot_Eta_prec, Sigma_Choleskys, discrete_priors, grainSize)
}

sample_h2s <- function(log_ps, grainSize) {
    .Call(BSFG_sample_h2s, log_ps, grainSize)
}

sample_h2s_discrete_MH_c <- function(Y, tot_Eta_prec, discrete_priors, h2_index, h2s_matrix, Sigma_Choleskys, r_draws, state_draws, step_size, grainSize) {
    .Call(BSFG_sample_h2s_discrete_MH_c, Y, tot_Eta_prec, discrete_priors, h2_index, h2s_matrix, Sigma_Choleskys, r_draws, state_draws, step_size, grainSize)
}

sample_coefs_hierarchical_parallel_sparse_c_Eigen <- function(Qt, Eta, W, X, resid_prec, prior_mean, prior_prec, grainSize) {
    .Call(BSFG_sample_coefs_hierarchical_parallel_sparse_c_Eigen, Qt, Eta, W, X, resid_prec, prior_mean, prior_prec, grainSize)
}

sample_delta_c_Eigen <- function(delta, tauh, scores, delta_1_rate, delta_2_rate, randg_draws) {
    .Call(BSFG_sample_delta_c_Eigen, delta, tauh, scores, delta_1_rate, delta_2_rate, randg_draws)
}

rgig_multiple <- function(n, lambda, chi, psi) {
    .Call(BSFG_rgig_multiple, n, lambda, chi, psi)
}

