// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sample_coefs_parallel_sparse_c
arma::mat sample_coefs_parallel_sparse_c(arma::mat UtEta, arma::mat UtW, arma::vec h2, arma::vec tot_Eta_prec, arma::vec s, arma::mat prior_mean, arma::mat prior_prec, int grainSize);
RcppExport SEXP BSFG_sample_coefs_parallel_sparse_c(SEXP UtEtaSEXP, SEXP UtWSEXP, SEXP h2SEXP, SEXP tot_Eta_precSEXP, SEXP sSEXP, SEXP prior_meanSEXP, SEXP prior_precSEXP, SEXP grainSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type UtEta(UtEtaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type UtW(UtWSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h2(h2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tot_Eta_prec(tot_Eta_precSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prior_mean(prior_meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prior_prec(prior_precSEXP);
    Rcpp::traits::input_parameter< int >::type grainSize(grainSizeSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_coefs_parallel_sparse_c(UtEta, UtW, h2, tot_Eta_prec, s, prior_mean, prior_prec, grainSize));
    return rcpp_result_gen;
END_RCPP
}
// sample_tot_prec_sparse_c
arma::rowvec sample_tot_prec_sparse_c(arma::mat Eta, arma::vec h2, double tot_Eta_prec_shape, double tot_Eta_prec_rate, List invert_aI_bZKZ);
RcppExport SEXP BSFG_sample_tot_prec_sparse_c(SEXP EtaSEXP, SEXP h2SEXP, SEXP tot_Eta_prec_shapeSEXP, SEXP tot_Eta_prec_rateSEXP, SEXP invert_aI_bZKZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h2(h2SEXP);
    Rcpp::traits::input_parameter< double >::type tot_Eta_prec_shape(tot_Eta_prec_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type tot_Eta_prec_rate(tot_Eta_prec_rateSEXP);
    Rcpp::traits::input_parameter< List >::type invert_aI_bZKZ(invert_aI_bZKZSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_tot_prec_sparse_c(Eta, h2, tot_Eta_prec_shape, tot_Eta_prec_rate, invert_aI_bZKZ));
    return rcpp_result_gen;
END_RCPP
}
// sample_h2s_discrete_given_p_sparse_c
arma::rowvec sample_h2s_discrete_given_p_sparse_c(arma::mat Eta, int h2_divisions, arma::vec h2_priors, arma::vec Tot_prec, List invert_aI_bZKZ);
RcppExport SEXP BSFG_sample_h2s_discrete_given_p_sparse_c(SEXP EtaSEXP, SEXP h2_divisionsSEXP, SEXP h2_priorsSEXP, SEXP Tot_precSEXP, SEXP invert_aI_bZKZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< int >::type h2_divisions(h2_divisionsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h2_priors(h2_priorsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Tot_prec(Tot_precSEXP);
    Rcpp::traits::input_parameter< List >::type invert_aI_bZKZ(invert_aI_bZKZSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_h2s_discrete_given_p_sparse_c(Eta, h2_divisions, h2_priors, Tot_prec, invert_aI_bZKZ));
    return rcpp_result_gen;
END_RCPP
}
// sample_randomEffects_parallel_sparse_c
arma::mat sample_randomEffects_parallel_sparse_c(arma::mat Eta, arma::sp_mat Z, arma::vec tot_prec, arma::vec h2, List invert_aZZt_Kinv, int grainSize);
RcppExport SEXP BSFG_sample_randomEffects_parallel_sparse_c(SEXP EtaSEXP, SEXP ZSEXP, SEXP tot_precSEXP, SEXP h2SEXP, SEXP invert_aZZt_KinvSEXP, SEXP grainSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Eta(EtaSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tot_prec(tot_precSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h2(h2SEXP);
    Rcpp::traits::input_parameter< List >::type invert_aZZt_Kinv(invert_aZZt_KinvSEXP);
    Rcpp::traits::input_parameter< int >::type grainSize(grainSizeSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_randomEffects_parallel_sparse_c(Eta, Z, tot_prec, h2, invert_aZZt_Kinv, grainSize));
    return rcpp_result_gen;
END_RCPP
}
// sample_factors_scores_sparse_c
arma::mat sample_factors_scores_sparse_c(arma::mat Eta_tilde, arma::mat prior_mean, arma::mat Lambda, arma::vec resid_Eta_prec, arma::vec F_e_prec);
RcppExport SEXP BSFG_sample_factors_scores_sparse_c(SEXP Eta_tildeSEXP, SEXP prior_meanSEXP, SEXP LambdaSEXP, SEXP resid_Eta_precSEXP, SEXP F_e_precSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Eta_tilde(Eta_tildeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type prior_mean(prior_meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type resid_Eta_prec(resid_Eta_precSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type F_e_prec(F_e_precSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_factors_scores_sparse_c(Eta_tilde, prior_mean, Lambda, resid_Eta_prec, F_e_prec));
    return rcpp_result_gen;
END_RCPP
}
// GSVD_2_c
List GSVD_2_c(arma::mat K, arma::mat B);
RcppExport SEXP BSFG_GSVD_2_c(SEXP KSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(GSVD_2_c(K, B));
    return rcpp_result_gen;
END_RCPP
}
// sample_delta_c
arma::rowvec sample_delta_c(arma::vec delta, arma::vec tauh, arma::mat Lambda_prec, double delta_1_shape, double delta_1_rate, double delta_2_shape, double delta_2_rate, arma::mat Lambda2, int times);
RcppExport SEXP BSFG_sample_delta_c(SEXP deltaSEXP, SEXP tauhSEXP, SEXP Lambda_precSEXP, SEXP delta_1_shapeSEXP, SEXP delta_1_rateSEXP, SEXP delta_2_shapeSEXP, SEXP delta_2_rateSEXP, SEXP Lambda2SEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tauh(tauhSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda_prec(Lambda_precSEXP);
    Rcpp::traits::input_parameter< double >::type delta_1_shape(delta_1_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type delta_1_rate(delta_1_rateSEXP);
    Rcpp::traits::input_parameter< double >::type delta_2_shape(delta_2_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type delta_2_rate(delta_2_rateSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda2(Lambda2SEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_delta_c(delta, tauh, Lambda_prec, delta_1_shape, delta_1_rate, delta_2_shape, delta_2_rate, Lambda2, times));
    return rcpp_result_gen;
END_RCPP
}
// log_binom_c
double log_binom_c(arma::vec beta, arma::mat X, arma::vec y, arma::vec N, arma::vec mu, arma::vec sigma2);
RcppExport SEXP BSFG_log_binom_c(SEXP betaSEXP, SEXP XSEXP, SEXP ySEXP, SEXP NSEXP, SEXP muSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(log_binom_c(beta, X, y, N, mu, sigma2));
    return rcpp_result_gen;
END_RCPP
}
